---

- name: "UNIFI-CONTROLLER | Configure"
  ansible.builtin.import_tasks: config.yml
  tags:
    - unifi_configure

- name: "UNIFI-CONTROLLER | Install"
  ansible.builtin.import_tasks: install.yml
  tags:
    - unifi_install
