---
- name: Clean up
  hosts: all
  gather_facts: true
  tasks:
    - name: "UNIFI-CONTROLLER | Load the defaults."
      ansible.builtin.include_vars:
        dir: "../../defaults"

    - name: "UNIFI-CONTROLLER | Check if the docker-compose file exists."
      ansible.builtin.stat:
        path: "{{ unifi_config_path  | expanduser | realpath }}/docker-compose.yml"
      register: "docker_compose_file"

    - name: "UNIFI-CONTROLLER | Remove docker-compose."
      community.docker.docker_compose:
        project_src: "{{ unifi_config_path | expanduser | realpath }}/"
        build: false
        state: absent
      when: "docker_compose_file.stat.exists"
      become: false

    - name: "UNIFI-CONTROLLER | Remove the docker-compose file"
      ansible.builtin.file:
        path: "{{ unifi_config_path | expanduser | realpath }}/docker-compose.yml"
        state: "absent"
      when: "docker_compose_file.stat.exists"
